### ISSUE TITLE
As a visitor I can register for a new account

### ISSUE THREAD

**Issue by A23W10** [kanzucode/angie-server#20]
###  Registration Form 

> **Register as an individual or family**

>**Get Visitor's Details i.e.**
- [ ] **First Name** [Input text box]
- [ ] **Last Name** [Input text box]
- [ ] **Email Address** 
- [ ] **Mobile Number** 
- [ ] **Date of Birth** 
- [ ] **Country of Residence** [_Drop-down list of countries_]
- [ ] **Place of Residence** [Input text box]
- [ ] **Worship Harvest Location** [_Drop-down list of locations to pick from_]
- [ ] **Missional Community (MC) Name** [_Drop-down list of MCs to pick from (If one does not belong to one they can select None)_]
- [ ] **Submit button** [_This will lead to a page (Profile Page) that shows the visitor the details they have input and also sends visitor email confirming their account registration_]

**Comment by MariamNaiga** [comment]
I would like to suggest an enhancement to the registration form. Could we register a family rather than an individual person to make it more convenient for the visitor. For example, a family of four would enter information about each family member in one registration form rather than in four different registration forms.

**Comment by A23W10** [comment]
@MariamNaiga thanks for the suggestion, hadn't factored in the monotony of each member of a family registering by themselves 😅
